<?php

namespace QTH\NetMapBundle\Repository;

/**
 * PlugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlugRepository extends \Doctrine\ORM\EntityRepository
{
}
