<?php

namespace QTH\NetMapBundle\Repository;

/**
 * RouterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouterRepository extends \Doctrine\ORM\EntityRepository
{
}
