<?php

namespace QTH\NetMapBundle\Repository;

/**
 * VlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VlanRepository extends \Doctrine\ORM\EntityRepository
{
}
